name: Semgrep

on:
  # Scan changed files in PRs, block on new issues only (existing issues ignored)
  pull_request: {}

  #   Scan all files on branches, block on any issues
  push:
    branches: ["main"]

  release:
    types: [published]

  # Schedule this job to run at a certain time, using cron syntax
  # Note that * is a special character in YAML so you have to quote this string
  schedule:
    - cron: '30 0 1,15 * *' # scheduled for 00:30 UTC on both the 1st and 15th of the month

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#  workflow_run:
#    workflows: [ "ci" ]
#    branches: [ main ]
#    types:
#      - completed

jobs:
  semgrep:
    name: scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep@ed5809b8dc02d9e87d93018e1e7e9dbdcf592ecd4a0da1c35f8df786ca41a982
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    steps:
      # Fetch project source
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep
        run: semgrep ci
        env:
          SEMGREP_RULES: |
            p/security-audit
            p/secrets
            p/ci
            p/r2c
            p/r2c-ci
            p/docker
            p/dockerfile
            p/command-injection
