name: Release Please

on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
#      - name: Import GPG key
#        id: import-gpg
#        uses: crazy-max/ghaction-import-gpg@v5
#        with:
#          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
#          passphrase: ${{ secrets.GPG_PASSPHRASE }}
#          git_config_global: true
#          git_user_signingkey: true
#          git_commit_gpgsign: true

#      - name: Setup Bot
#        run: |
#          git config --global user.email "${{ steps.import-gpg.outputs.email }}"
#          git config --global user.name "${{ steps.import-gpg.outputs.name }}"

      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          release-type: go
          changelog-path: CHANGELOG.md
          signoff: "nickaguilarh[bot] <nickaguilarh@gmail.com>"
          package-name: ${{ github.repository }}
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
